sudo: required
services:
  - docker

before_install:
  - docker build -t nrakwtnb/practice-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nrakwtnb/practice-docker-react npm run test
  #- docker run nrakwtnb/practice-docker-react npm run test -- --coverage
