sudo: required
services:
  - docker

before_install:
  - docker build -t nrakwtnb/practice-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nrakwtnb/practice-docker-react npm run test
  #- docker run nrakwtnb/practice-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-133425340328"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
